### ISSUE TITLE
Create a view in the WebApp to show the results of the aggregations

### ISSUE THREAD

**Issue by grafvonb** [okoeth/serverless-demo#15]
The App should also leverage Lambdas

**Comment by okoeth** [comment]
The results from the collect-buzzwords shows how often "secondary" hash tags come with a "primary" hash-tag. For example #culture ("secondary") was mentioned 117 times next to #devops ("primary"). From a UI perspective we could just show a list of "primary" hashtags (has header), and a table of top 10 "secondary" tags. (Or if that results in a too long page, we could also provide the primary tags in a drop down or a side bar and only show one set of "secondary" tags.)

**Comment by grafvonb** [comment]
Done
